export const initialRoster = {
  activeRoster: {},
  collection: {
    batman: {
      name: "batman",
      displayName: "Batman (Prime Earth)",
      displayIcon: "/images/batman/batmanDown2.png",
      spriteSheet: "/images/batman/batmanSpriteSheet.png",
      x: 48,
      y: 0,
      movement: 2,
    },
    robin: {
      name: "robin",
      displayName: "Robin (Dick Grayson)(Prime Earth)",
      displayIcon: "/images/robin/robinDown2.png",
      spriteSheet: "/images/robin/robinNightwingSpriteSheet.png",
      x: 48,
      y: 0,
      movement: 2,
    },
    nightwing: {
      name: "nightwing",
      displayName: "Nightwing (Dick Grayson)(Prime Earth)",
      displayIcon: "/images/nightwing/nightwingDown2.png",
      spriteSheet: "/images/robin/robinNightwingSpriteSheet.png",
      x: 192,
      y: 0,
      movement: 3,
    },
    superman: {
      name: "superman",
      displayName: "Superman (Clark Kent)(Prime Earth)",
      displayIcon: "/images/superman/supermanDown2.png",
      spriteSheet: "/images/superman/supermanSpriteSheet.png",
      x: 48,
      y: 0,
      movement: 2,
    },
    drMultiverse: {
      name: "drMultiverse",
      displayName: "Dr. Multiverse (Maya Chamara)(Earth 8)",
      displayIcon: "/images/drMultiverse/drMultiverseDown2.png",
      spriteSheet: "/images/drMultiverse/drMultiverseSpriteSheet.png",
      x: 48,
      y: 0,
      movement: 2,
    },
  },
};
