export const initialRoster = {
  activeRoster: {},
  collection: {
    batman: {
      id: "batman",
      name: "Batman (Prime Earth)",
      icon: "/images/batman/batmanDown2.png",
      spriteSheet: "/images/batman/batmanSpriteSheet.png",
      x: 48,
      y: 0,
      moveRange: 2,
    },
    robin: {
      id: "robin",
      name: "Robin (Dick Grayson)(Prime Earth)",
      icon: "/images/robin/robinDown2.png",
      spriteSheet: "/images/robin/robinNightwingSpriteSheet.png",
      x: 48,
      y: 0,
      moveRange: 2,
    },
    nightwing: {
      id: "nightwing",
      name: "Nightwing (Dick Grayson)(Prime Earth)",
      icon: "/images/nightwing/nightwingDown2.png",
      spriteSheet: "/images/nightwing/nightwingSpriteSheet.png",
      x: 48,
      y: 0,
      moveRange: 3,
    },
    superman: {
      id: "superman",
      name: "Superman (Clark Kent)(Prime Earth)",
      icon: "/images/superman/supermanDown2.png",
      spriteSheet: "/images/superman/supermanSpriteSheet.png",
      x: 48,
      y: 0,
      moveRange: 2,
    },
    drMultiverse: {
      id: "drMultiverse",
      name: "Dr. Multiverse (Maya Chamara)(Earth 8)",
      icon: "/images/drMultiverse/drMultiverseDown2.png",
      spriteSheet: "/images/drMultiverse/drMultiverseSpriteSheet.png",
      x: 48,
      y: 0,
      moveRange: 2,
    },
  },
};
